/**
 * Generates THIRD-PARTY-LICENSES.md from the runtime dependency closure.
 *
 * The published CLIs bundle their runtime dependencies into `dist/`, which
 * strips the per-package license headers. To satisfy the (permissive) MIT /
 * ISC / BSD terms of those bundled packages, we collect each one's license
 * text into a single notices file shipped alongside the bundle.
 *
 * Roots are the packages actually imported by src/. Dev-only tooling
 * (biome, typescript, @types/*) is intentionally excluded — none of it is
 * bundled into dist/.
 */

import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOTS = ['node-pkware', 'command-line-args', 'winston', 'mdb-reader'];
const NODE_MODULES = 'node_modules';

interface Pkg {
  name: string;
  version: string;
  license?: string;
  licenses?: { type: string }[];
  author?: unknown;
  dependencies?: Record<string, string>;
  homepage?: string;
}

function readPkg(name: string): Pkg | undefined {
  try {
    return JSON.parse(readFileSync(join(NODE_MODULES, name, 'package.json'), 'utf8')) as Pkg;
  } catch {
    return undefined;
  }
}

function readLicenseText(name: string): string | undefined {
  const dir = join(NODE_MODULES, name);
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return undefined;
  }
  const file = entries.find(e => /^(licen[sc]e|copying)(\.|$)/i.test(e));
  if (!file) return undefined;
  try {
    return readFileSync(join(dir, file), 'utf8').trim();
  } catch {
    return undefined;
  }
}

function licenseId(pkg: Pkg): string {
  if (typeof pkg.license === 'string') return pkg.license;
  if (pkg.licenses?.length) return pkg.licenses.map(l => l.type).join(', ');
  return 'UNKNOWN';
}

// Resolve the transitive closure of runtime dependencies.
const seen = new Set<string>();
const queue = [...ROOTS];
while (queue.length > 0) {
  const name = queue.shift() as string;
  if (seen.has(name)) continue;
  seen.add(name);
  const pkg = readPkg(name);
  if (pkg?.dependencies) queue.push(...Object.keys(pkg.dependencies));
}

const names = [...seen].sort();

let unknown = 0;
const sections: string[] = [];
for (const name of names) {
  const pkg = readPkg(name);
  if (!pkg) continue;
  const id = licenseId(pkg);
  if (id === 'UNKNOWN') unknown++;
  const text = readLicenseText(name);
  const header = `## ${name}@${pkg.version} (${id})`;
  const link = pkg.homepage ? `\n${pkg.homepage}\n` : '';
  const body = text ? `\n\`\`\`\n${text}\n\`\`\`\n` : '\n_(no license file shipped in the package; see the SPDX id above)_\n';
  sections.push(`${header}\n${link}${body}`);
}

const preamble = `# Third-party licenses

The \`ewd\` and \`ewe\` executables in \`dist/\` are bundled with the following
third-party packages. Their license texts are reproduced below. This file is
generated by \`scripts/collect-licenses.ts\`.

Bundled packages (${names.length}): ${names.join(', ')}.
`;

await Bun.write('THIRD-PARTY-LICENSES.md', `${preamble}\n${sections.join('\n')}`);
console.log(`Wrote THIRD-PARTY-LICENSES.md for ${names.length} packages (${unknown} with no SPDX id).`);
